const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Autenticação',
      items: [
        'autenticacao/login',
      ]
    }
  ]
};

export default sidebars;